#ifndef INDEX_SEGMENTATION_CHANNELSEGMENTATIONSTRATEGY_SAMPLINGCHSSSAMPLINGPARAMS_HPP
#define INDEX_SEGMENTATION_CHANNELSEGMENTATIONSTRATEGY_SAMPLINGCHSSSAMPLINGPARAMS_HPP

#include "Util/Types/Numbers.hpp"

struct SamplingChSSSamplingParams {
    bool m_normalized = true;
    uint m_segment_len = 1;
    uint m_sample_size = 0;
};

#endif  // INDEX_SEGMENTATION_CHANNELSEGMENTATIONSTRATEGY_SAMPLINGCHSSSAMPLINGPARAMS_HPP
