#ifndef SERIALIZATION_REGISTRATION_HPP
#define SERIALIZATION_REGISTRATION_HPP

#include <cereal/archives/binary.hpp>
#include <cereal/archives/json.hpp>
#include <cereal/types/memory.hpp>
#include <cereal/types/polymorphic.hpp>
#include <cereal/types/vector.hpp>

#include "Index/Entry/Envelope.hpp"
#include "Index/Entry/Paa.hpp"
#include "Index/EnvelopeIndex/Tree/EnvelopeNode.hpp"
#include "Index/Segmentation/ChannelSegmentationStrategy/MultiChSegmentationStrategy.hpp"
#include "Index/Segmentation/ChannelSegmentationStrategy/ScoreBased/EnvStatsChSegmentationStrategy.hpp"
#include "Index/Segmentation/ChannelSegmentationStrategy/ScoreBased/EnvWidthChSegmentationStrategy.hpp"
#include "Index/Segmentation/ChannelSegmentationStrategy/ScoreBased/ScoreBasedChSegmentationStrategy.hpp"
#include "Index/Segmentation/ChannelSegmentationStrategy/SingleChSegmentationStrategy.hpp"
#include "Index/Segmentation/SegmentationStrategy/AdaptiveSegmentationStrategy.hpp"
#include "Index/Segmentation/SegmentationStrategy/UniformSegmentationStrategy.hpp"
#include "Index/iSaxIndex/FinalizedISaxIndex.hpp"
#include "Index/iSaxIndex/FinalizedISaxNode.hpp"

// Register archive types
CEREAL_REGISTER_ARCHIVE(cereal::BinaryInputArchive)
CEREAL_REGISTER_ARCHIVE(cereal::JSONInputArchive)
CEREAL_REGISTER_ARCHIVE(cereal::BinaryOutputArchive)
CEREAL_REGISTER_ARCHIVE(cereal::JSONOutputArchive)

// Register index entries
CEREAL_REGISTER_TYPE(Paa)
CEREAL_REGISTER_POLYMORPHIC_RELATION(IEntryData, Paa)
CEREAL_REGISTER_TYPE(Envelope)
CEREAL_REGISTER_POLYMORPHIC_RELATION(IEntryData, Envelope)

// Register iSAX node types
CEREAL_REGISTER_TYPE(iSaxInternalNodeArgs<PaaTag>)
CEREAL_REGISTER_TYPE(iSaxInternalNodeArgs<EnvelopeTag>)

CEREAL_REGISTER_TYPE(iSaxEnvelopeInternalNodeArgs)
CEREAL_REGISTER_POLYMORPHIC_RELATION(iSaxInternalNodeArgs<PaaTag>, iSaxEnvelopeInternalNodeArgs)
CEREAL_REGISTER_POLYMORPHIC_RELATION(iSaxInternalNodeArgs<EnvelopeTag>, iSaxEnvelopeInternalNodeArgs)

CEREAL_REGISTER_TYPE(FinalizedISaxInternal<PaaTag>)
CEREAL_REGISTER_TYPE(FinalizedISaxInternal<EnvelopeTag>)
CEREAL_REGISTER_POLYMORPHIC_RELATION(FinalizedISaxNode<PaaTag>, FinalizedISaxInternal<PaaTag>)
CEREAL_REGISTER_POLYMORPHIC_RELATION(FinalizedISaxNode<EnvelopeTag>, FinalizedISaxInternal<EnvelopeTag>)

CEREAL_REGISTER_TYPE(FinalizedISaxLeaf<PaaTag>)
CEREAL_REGISTER_TYPE(FinalizedISaxLeaf<EnvelopeTag>)
CEREAL_REGISTER_POLYMORPHIC_RELATION(FinalizedISaxNode<PaaTag>, FinalizedISaxLeaf<PaaTag>)
CEREAL_REGISTER_POLYMORPHIC_RELATION(FinalizedISaxNode<EnvelopeTag>, FinalizedISaxLeaf<EnvelopeTag>)

// Register envelope node types
CEREAL_REGISTER_TYPE(EnvelopeInternal)
CEREAL_REGISTER_POLYMORPHIC_RELATION(EnvelopeNode, EnvelopeInternal)

CEREAL_REGISTER_TYPE(EnvelopeLeaf)
CEREAL_REGISTER_POLYMORPHIC_RELATION(EnvelopeNode, EnvelopeLeaf)

// Register segmentation strategies
CEREAL_REGISTER_TYPE(UniformSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(ISegmentationStrategy, UniformSegmentationStrategy)

CEREAL_REGISTER_TYPE(AdaptiveSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(ISegmentationStrategy, AdaptiveSegmentationStrategy)

// Register channel segmentation strategies
CEREAL_REGISTER_TYPE(SingleChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(IChannelSegmentationStrategy, SingleChSegmentationStrategy)
CEREAL_REGISTER_TYPE(MultiChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(IChannelSegmentationStrategy, MultiChSegmentationStrategy)
CEREAL_REGISTER_TYPE(SamplingChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(MultiChSegmentationStrategy, SamplingChSegmentationStrategy)
CEREAL_REGISTER_TYPE(ScoreBasedChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(SamplingChSegmentationStrategy, ScoreBasedChSegmentationStrategy)
CEREAL_REGISTER_TYPE(EnvWidthChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(ScoreBasedChSegmentationStrategy, EnvWidthChSegmentationStrategy)
CEREAL_REGISTER_TYPE(EnvStatsChSegmentationStrategy)
CEREAL_REGISTER_POLYMORPHIC_RELATION(ScoreBasedChSegmentationStrategy, EnvStatsChSegmentationStrategy)

#endif  // SERIALIZATION_REGISTRATION_HPP
