#ifndef ENUMS_ENVELOPECONFIGGENERATORTYPE_HPP
#define ENUMS_ENVELOPECONFIGGENERATORTYPE_HPP

#include "Util/HelperFuncs/Enums.hpp"

enum EnvelopeConfigGeneratorType { GRID, RANDOM };

DEFINE_ENUM_CONSTS_NO_EXTRA(EnvelopeConfigGeneratorType, ENV_CONFIG_GENERATOR_TYPE, false);

#endif  // ENUMS_ENVELOPECONFIGGENERATORTYPE_HPP
