#ifndef UTIL_HELPERFUNCS_PARALLELISM_HPP
#define UTIL_HELPERFUNCS_PARALLELISM_HPP

#ifndef DISABLE_PARALLELISM
#define OMP_PRAGMA(x) _Pragma(#x)
#else
#define OMP_PRAGMA(x)
#endif

#endif  // UTIL_HELPERFUNCS_PARALLELISM_HPP
